### PR TITLE
Try Windows build

### PR DESCRIPTION
**Pull request by ehfd**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@hmaarrfk It seems that rerendering generates the Windows CI file pointing to the old `m2w64-toolchain` instead of `m2w64-sysroot`.

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by ehfd** [comment]
@conda-forge-admin, please rerender

**Comment by hmaarrfk** [comment]
ah i was looking for a migration. good catch!

**Comment by ehfd** [comment]
And now we are back to this issue:

```
config.status: executing depfiles commands
config.status: executing libtool commands
+ make -j2
Making all in src
make[1]: Entering directory '/d/bld/xorg-libxxf86vm_1727975429446/work/src'
make  all-am
make[2]: Entering directory '/d/bld/xorg-libxxf86vm_1727975429446/work/src'
/bin/sh ../libtool  --tag=CC   --mode=compile x86_64-w64-mingw32-gcc.exe -DHAVE_CONFIG_H -I.  -I../include  -pthread -ID:/bld/xorg-libxxf86vm_1727975429446/_h_env/Library/include -DMALLOC_0_RETURNS_NULL -g -O2 -c -o XF86VMode.lo XF86VMode.c
libtool: compile:  x86_64-w64-mingw32-gcc.exe -DHAVE_CONFIG_H -I. -I../include -pthread -ID:/bld/xorg-libxxf86vm_1727975429446/_h_env/Library/include -DMALLOC_0_RETURNS_NULL -g -O2 -c XF86VMode.c  -DDLL_EXPORT -DPIC -o .libs/XF86VMode.o
/bin/sh ../libtool  --tag=CC   --mode=link x86_64-w64-mingw32-gcc.exe -pthread -ID:/bld/xorg-libxxf86vm_1727975429446/_h_env/Library/include -DMALLOC_0_RETURNS_NULL -g -O2 -version-number 1:0:0 -LD:/bld/xorg-libxxf86vm_1727975429446/_build_env/Library/x86_64-w64-mingw32/sysroot/usr/lib -o libXxf86vm.la -rpath D:/bld/xorg-libxxf86vm_1727975429446/_h_env/Library/lib XF86VMode.lo -LD:/bld/xorg-libxxf86vm_1727975429446/_h_env/Library/lib -lXext -lX11 -lxcb -lws2_32 -lXau -pthread -lXdmcp 
libtool:   error: can't build x86_64-pc-msys shared library unless -no-undefined is specified
make[2]: *** [Makefile:448: libXxf86vm.la] Error 1
make[1]: *** [Makefile:363: all] Error 2
make: *** [Makefile:460: all-recursive] Error 1
make[2]: Leaving directory '/d/bld/xorg-libxxf86vm_1727975429446/work/src'
make[1]: Leaving directory '/d/bld/xorg-libxxf86vm_1727975429446/work/src'
Traceback (most recent call last):
  File "C:\Miniforge\Lib\site-packages\conda_build\build.py", line 2508, in build
    windows.build(
  File "C:\Miniforge\Lib\site-packages\conda_build\windows.py", line 339, in build
    check_call_env(
  File "C:\Miniforge\Lib\site-packages\conda_build\utils.py", line 404, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Miniforge\Lib\site-packages\conda_build\utils.py", line 380, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['cmd.exe', '/d', '/c', 'conda_build.bat']' returned non-zero exit status 1.
```

@isuruf @pkgw Any opinion?

**Comment by pkgw** [comment]
From looking at the other X.org libraries, it seems that they simple include the `-no-undefined` flag in the `LDFLAGS` definitions for their libraries in `Makefile.am`. This package omits it, presumably because no one builds  it on Windows. Patching the source file to add the flag fixes the build. In principle this fix should be submitted upstream, but this library looks to be pretty much unmaintained these days.

**Comment by ehfd** [comment]
Added relevant issue: https://gitlab.freedesktop.org/xorg/lib/libxxf86vm/-/issues/2

**Comment by ehfd** [comment]
@pkgw Note that https://github.com/conda-forge/xorg-libxxf86vm-feedstock/blob/main/recipe/build.sh is a reference file that combines your and my preferences for the X11 `build.sh` stack overall, and should work mostly everywhere.

**Pull request merged**
